### ISSUE TITLE
Relicense / next major version

### ISSUE THREAD

**Issue by ericsizemore** [ericsizemore/simple_counter#13]
To allow this package to be adopted by other projects, it's time to finally move the license of this package from the LGPLv3 to something more permissive, like MIT.

The current goal to make this change will be in the next major version, 6.0.0. To prevent any potential issues, v6 will be a complete rewrite so that no LGPL code remains in the project.

Version 5.0.1 and older will still be LGPLv3 licensed.

**Tasks for v6:**

- [x] Create a new develop branch for the rewrite
- [x] Decide on a new public api, interfaces, etc.
- [x] Design new counter images
- [x] Implement #4 
- [ ] (possibly) Implement #1
- [ ] ... other tasks tbd ...

I'm open to feedback, feature requests, recommendations, etc. :)

**Comment by ericsizemore** [comment]
New branch for development:

https://github.com/ericsizemore/simple_counter/tree/6.x-dev
